/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface CampaignFactoryInterface extends utils.Interface {
  functions: {
    "accountInTransit(address)": FunctionFragment;
    "accountTransitStartedBy(address)": FunctionFragment;
    "approvedCampaignTransactionConfig(string)": FunctionFragment;
    "campaignCategories(uint256)": FunctionFragment;
    "campaignCount()": FunctionFragment;
    "campaignFactoryAddress()": FunctionFragment;
    "campaignImplementation()": FunctionFragment;
    "campaignRequestsImplementation()": FunctionFragment;
    "campaignRevenueFromCommissions(address)": FunctionFragment;
    "campaignRewardsImplementation()": FunctionFragment;
    "campaignTransactionConfig(string)": FunctionFragment;
    "campaignTransactionConfigList(uint256)": FunctionFragment;
    "campaignVotesImplementation()": FunctionFragment;
    "campaigns(address)": FunctionFragment;
    "categoryCommission(uint256)": FunctionFragment;
    "categoryCount()": FunctionFragment;
    "categoryTitleIsTaken(string)": FunctionFragment;
    "factoryRevenue()": FunctionFragment;
    "governance()": FunctionFragment;
    "isUserTrustee(address,address)": FunctionFragment;
    "paused()": FunctionFragment;
    "tokens(address)": FunctionFragment;
    "trustees(uint256)": FunctionFragment;
    "userCount()": FunctionFragment;
    "userExists(address)": FunctionFragment;
    "userTrusteeCount(address)": FunctionFragment;
    "users(address)": FunctionFragment;
    "__CampaignFactory_init(address,address,address,address,address,uint256[15])": FunctionFragment;
    "setCampaignImplementation(address)": FunctionFragment;
    "setCampaignRewardImplementation(address)": FunctionFragment;
    "setCampaignRequestImplementation(address)": FunctionFragment;
    "setCampaignVoteImplementation(address)": FunctionFragment;
    "addFactoryTransactionConfig(string)": FunctionFragment;
    "setCampaignTransactionConfig(string,uint256)": FunctionFragment;
    "setDefaultCommission(uint256,uint256)": FunctionFragment;
    "setCategoryCommission(uint256,uint256,uint256)": FunctionFragment;
    "addToken(address,bool,string)": FunctionFragment;
    "toggleAcceptedToken(address,bool)": FunctionFragment;
    "canManageCampaigns(address)": FunctionFragment;
    "receiveCampaignCommission(address,uint256)": FunctionFragment;
    "signUp(string)": FunctionFragment;
    "userIsVerified(address)": FunctionFragment;
    "initiateUserTransfer(address,bool)": FunctionFragment;
    "deactivateAccountTransfer()": FunctionFragment;
    "addTrustee(address)": FunctionFragment;
    "removeTrustee(uint256)": FunctionFragment;
    "toggleUserApproval(address,bool)": FunctionFragment;
    "createCampaign(uint256,bool,string)": FunctionFragment;
    "activateCampaign(address)": FunctionFragment;
    "approveCampaign(address)": FunctionFragment;
    "modifyCampaignCategory(address,uint256)": FunctionFragment;
    "createCategory(bool,string)": FunctionFragment;
    "modifyCategory(uint256,bool,string)": FunctionFragment;
    "unpauseCampaign()": FunctionFragment;
    "pauseCampaign()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accountInTransit"
      | "accountTransitStartedBy"
      | "approvedCampaignTransactionConfig"
      | "campaignCategories"
      | "campaignCount"
      | "campaignFactoryAddress"
      | "campaignImplementation"
      | "campaignRequestsImplementation"
      | "campaignRevenueFromCommissions"
      | "campaignRewardsImplementation"
      | "campaignTransactionConfig"
      | "campaignTransactionConfigList"
      | "campaignVotesImplementation"
      | "campaigns"
      | "categoryCommission"
      | "categoryCount"
      | "categoryTitleIsTaken"
      | "factoryRevenue"
      | "governance"
      | "isUserTrustee"
      | "paused"
      | "tokens"
      | "trustees"
      | "userCount"
      | "userExists"
      | "userTrusteeCount"
      | "users"
      | "__CampaignFactory_init"
      | "setCampaignImplementation"
      | "setCampaignRewardImplementation"
      | "setCampaignRequestImplementation"
      | "setCampaignVoteImplementation"
      | "addFactoryTransactionConfig"
      | "setCampaignTransactionConfig"
      | "setDefaultCommission"
      | "setCategoryCommission"
      | "addToken"
      | "toggleAcceptedToken"
      | "canManageCampaigns"
      | "receiveCampaignCommission"
      | "signUp"
      | "userIsVerified"
      | "initiateUserTransfer"
      | "deactivateAccountTransfer"
      | "addTrustee"
      | "removeTrustee"
      | "toggleUserApproval"
      | "createCampaign"
      | "activateCampaign"
      | "approveCampaign"
      | "modifyCampaignCategory"
      | "createCategory"
      | "modifyCategory"
      | "unpauseCampaign"
      | "pauseCampaign"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accountInTransit",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "accountTransitStartedBy",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedCampaignTransactionConfig",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCategories",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignFactoryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignRequestsImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignRevenueFromCommissions",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignRewardsImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaignTransactionConfig",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignTransactionConfigList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignVotesImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "campaigns", values: [string]): string;
  encodeFunctionData(
    functionFragment: "categoryCommission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "categoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "categoryTitleIsTaken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "factoryRevenue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isUserTrustee",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "tokens", values: [string]): string;
  encodeFunctionData(
    functionFragment: "trustees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "userCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "userExists", values: [string]): string;
  encodeFunctionData(
    functionFragment: "userTrusteeCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [string]): string;
  encodeFunctionData(
    functionFragment: "__CampaignFactory_init",
    values: [string, string, string, string, string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignRewardImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignRequestImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignVoteImplementation",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "addFactoryTransactionConfig",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignTransactionConfig",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultCommission",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCategoryCommission",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addToken",
    values: [string, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleAcceptedToken",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "canManageCampaigns",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveCampaignCommission",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "signUp", values: [string]): string;
  encodeFunctionData(
    functionFragment: "userIsVerified",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateUserTransfer",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAccountTransfer",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "addTrustee", values: [string]): string;
  encodeFunctionData(
    functionFragment: "removeTrustee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleUserApproval",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "activateCampaign",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "approveCampaign",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyCampaignCategory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCategory",
    values: [boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyCategory",
    values: [BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseCampaign",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pauseCampaign",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accountInTransit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountTransitStartedBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedCampaignTransactionConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCategories",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignFactoryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignRequestsImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignRevenueFromCommissions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignRewardsImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignTransactionConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignTransactionConfigList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignVotesImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "categoryCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "categoryTitleIsTaken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "factoryRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isUserTrustee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "trustees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userExists", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userTrusteeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "__CampaignFactory_init",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignRewardImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignRequestImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignVoteImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addFactoryTransactionConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignTransactionConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCategoryCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "toggleAcceptedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canManageCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveCampaignCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "signUp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userIsVerified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateUserTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAccountTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addTrustee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeTrustee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleUserApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyCampaignCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseCampaign",
    data: BytesLike
  ): Result;

  events: {
    "CampaignActivation(address)": EventFragment;
    "CampaignApproval(address)": EventFragment;
    "CampaignCategoryChange(address,uint256)": EventFragment;
    "CampaignDefaultCommissionUpdated(uint256)": EventFragment;
    "CampaignDeployed(address,address,address,address,address,uint256,bool)": EventFragment;
    "CampaignImplementationUpdated(address)": EventFragment;
    "CampaignRequestImplementationUpdated(address)": EventFragment;
    "CampaignRewardImplementationUpdated(address)": EventFragment;
    "CampaignTransactionConfigUpdated(string,uint256)": EventFragment;
    "CampaignVoteImplementationUpdated(address)": EventFragment;
    "CategoryAdded(uint256,bool,string)": EventFragment;
    "CategoryCommissionUpdated(uint256,uint256)": EventFragment;
    "CategoryModified(uint256,bool,string)": EventFragment;
    "Paused(address)": EventFragment;
    "TokenAdded(address,bool)": EventFragment;
    "TokenApproval(address,bool)": EventFragment;
    "TrusteeAdded(uint256,address)": EventFragment;
    "TrusteeRemoved(uint256,address)": EventFragment;
    "Unpaused(address)": EventFragment;
    "UserAdded(address)": EventFragment;
    "UserApproval(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CampaignActivation"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignApproval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignCategoryChange"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CampaignDefaultCommissionUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CampaignDeployed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CampaignImplementationUpdated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CampaignRequestImplementationUpdated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CampaignRewardImplementationUpdated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CampaignTransactionConfigUpdated"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "CampaignVoteImplementationUpdated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CategoryAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CategoryCommissionUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CategoryModified"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenApproval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TrusteeAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TrusteeRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UserApproval"): EventFragment;
}

export interface CampaignActivationEventObject {
  campaign: string;
}
export type CampaignActivationEvent = TypedEvent<
  [string],
  CampaignActivationEventObject
>;

export type CampaignActivationEventFilter =
  TypedEventFilter<CampaignActivationEvent>;

export interface CampaignApprovalEventObject {
  campaign: string;
}
export type CampaignApprovalEvent = TypedEvent<
  [string],
  CampaignApprovalEventObject
>;

export type CampaignApprovalEventFilter =
  TypedEventFilter<CampaignApprovalEvent>;

export interface CampaignCategoryChangeEventObject {
  campaign: string;
  newCategory: BigNumber;
}
export type CampaignCategoryChangeEvent = TypedEvent<
  [string, BigNumber],
  CampaignCategoryChangeEventObject
>;

export type CampaignCategoryChangeEventFilter =
  TypedEventFilter<CampaignCategoryChangeEvent>;

export interface CampaignDefaultCommissionUpdatedEventObject {
  commission: BigNumber;
}
export type CampaignDefaultCommissionUpdatedEvent = TypedEvent<
  [BigNumber],
  CampaignDefaultCommissionUpdatedEventObject
>;

export type CampaignDefaultCommissionUpdatedEventFilter =
  TypedEventFilter<CampaignDefaultCommissionUpdatedEvent>;

export interface CampaignDeployedEventObject {
  factory: string;
  campaign: string;
  campaignRewards: string;
  campaignRequests: string;
  campaignVotes: string;
  category: BigNumber;
  approved: boolean;
}
export type CampaignDeployedEvent = TypedEvent<
  [string, string, string, string, string, BigNumber, boolean],
  CampaignDeployedEventObject
>;

export type CampaignDeployedEventFilter =
  TypedEventFilter<CampaignDeployedEvent>;

export interface CampaignImplementationUpdatedEventObject {
  campaignImplementation: string;
}
export type CampaignImplementationUpdatedEvent = TypedEvent<
  [string],
  CampaignImplementationUpdatedEventObject
>;

export type CampaignImplementationUpdatedEventFilter =
  TypedEventFilter<CampaignImplementationUpdatedEvent>;

export interface CampaignRequestImplementationUpdatedEventObject {
  campaignRequestImplementation: string;
}
export type CampaignRequestImplementationUpdatedEvent = TypedEvent<
  [string],
  CampaignRequestImplementationUpdatedEventObject
>;

export type CampaignRequestImplementationUpdatedEventFilter =
  TypedEventFilter<CampaignRequestImplementationUpdatedEvent>;

export interface CampaignRewardImplementationUpdatedEventObject {
  campaignRewardImplementation: string;
}
export type CampaignRewardImplementationUpdatedEvent = TypedEvent<
  [string],
  CampaignRewardImplementationUpdatedEventObject
>;

export type CampaignRewardImplementationUpdatedEventFilter =
  TypedEventFilter<CampaignRewardImplementationUpdatedEvent>;

export interface CampaignTransactionConfigUpdatedEventObject {
  prop: string;
  value: BigNumber;
}
export type CampaignTransactionConfigUpdatedEvent = TypedEvent<
  [string, BigNumber],
  CampaignTransactionConfigUpdatedEventObject
>;

export type CampaignTransactionConfigUpdatedEventFilter =
  TypedEventFilter<CampaignTransactionConfigUpdatedEvent>;

export interface CampaignVoteImplementationUpdatedEventObject {
  campaignVoteImplementation: string;
}
export type CampaignVoteImplementationUpdatedEvent = TypedEvent<
  [string],
  CampaignVoteImplementationUpdatedEventObject
>;

export type CampaignVoteImplementationUpdatedEventFilter =
  TypedEventFilter<CampaignVoteImplementationUpdatedEvent>;

export interface CategoryAddedEventObject {
  categoryId: BigNumber;
  active: boolean;
  title: string;
}
export type CategoryAddedEvent = TypedEvent<
  [BigNumber, boolean, string],
  CategoryAddedEventObject
>;

export type CategoryAddedEventFilter = TypedEventFilter<CategoryAddedEvent>;

export interface CategoryCommissionUpdatedEventObject {
  categoryId: BigNumber;
  commission: BigNumber;
}
export type CategoryCommissionUpdatedEvent = TypedEvent<
  [BigNumber, BigNumber],
  CategoryCommissionUpdatedEventObject
>;

export type CategoryCommissionUpdatedEventFilter =
  TypedEventFilter<CategoryCommissionUpdatedEvent>;

export interface CategoryModifiedEventObject {
  categoryId: BigNumber;
  active: boolean;
  title: string;
}
export type CategoryModifiedEvent = TypedEvent<
  [BigNumber, boolean, string],
  CategoryModifiedEventObject
>;

export type CategoryModifiedEventFilter =
  TypedEventFilter<CategoryModifiedEvent>;

export interface PausedEventObject {
  account: string;
}
export type PausedEvent = TypedEvent<[string], PausedEventObject>;

export type PausedEventFilter = TypedEventFilter<PausedEvent>;

export interface TokenAddedEventObject {
  token: string;
  approval: boolean;
}
export type TokenAddedEvent = TypedEvent<
  [string, boolean],
  TokenAddedEventObject
>;

export type TokenAddedEventFilter = TypedEventFilter<TokenAddedEvent>;

export interface TokenApprovalEventObject {
  token: string;
  state: boolean;
}
export type TokenApprovalEvent = TypedEvent<
  [string, boolean],
  TokenApprovalEventObject
>;

export type TokenApprovalEventFilter = TypedEventFilter<TokenApprovalEvent>;

export interface TrusteeAddedEventObject {
  trusteeId: BigNumber;
  trusteeAddress: string;
}
export type TrusteeAddedEvent = TypedEvent<
  [BigNumber, string],
  TrusteeAddedEventObject
>;

export type TrusteeAddedEventFilter = TypedEventFilter<TrusteeAddedEvent>;

export interface TrusteeRemovedEventObject {
  trusteeId: BigNumber;
  trusteeAddress: string;
}
export type TrusteeRemovedEvent = TypedEvent<
  [BigNumber, string],
  TrusteeRemovedEventObject
>;

export type TrusteeRemovedEventFilter = TypedEventFilter<TrusteeRemovedEvent>;

export interface UnpausedEventObject {
  account: string;
}
export type UnpausedEvent = TypedEvent<[string], UnpausedEventObject>;

export type UnpausedEventFilter = TypedEventFilter<UnpausedEvent>;

export interface UserAddedEventObject {
  userId: string;
}
export type UserAddedEvent = TypedEvent<[string], UserAddedEventObject>;

export type UserAddedEventFilter = TypedEventFilter<UserAddedEvent>;

export interface UserApprovalEventObject {
  user: string;
  approval: boolean;
}
export type UserApprovalEvent = TypedEvent<
  [string, boolean],
  UserApprovalEventObject
>;

export type UserApprovalEventFilter = TypedEventFilter<UserApprovalEvent>;

export interface CampaignFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CampaignFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountInTransit(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    accountTransitStartedBy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    approvedCampaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    campaignCategories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        campaignCount: BigNumber;
        createdAt: BigNumber;
        updatedAt: BigNumber;
        title: string;
        active: boolean;
        exists: boolean;
      }
    >;

    campaignCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    campaignFactoryAddress(overrides?: CallOverrides): Promise<[string]>;

    campaignImplementation(overrides?: CallOverrides): Promise<[string]>;

    campaignRequestsImplementation(
      overrides?: CallOverrides
    ): Promise<[string]>;

    campaignRevenueFromCommissions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    campaignRewardsImplementation(overrides?: CallOverrides): Promise<[string]>;

    campaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    campaignTransactionConfigList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    campaignVotesImplementation(overrides?: CallOverrides): Promise<[string]>;

    campaigns(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        owner: string;
        createdAt: BigNumber;
        updatedAt: BigNumber;
        category: BigNumber;
        hashedCampaignInfo: string;
        active: boolean;
        approved: boolean;
      }
    >;

    categoryCommission(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    categoryCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    categoryTitleIsTaken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    factoryRevenue(overrides?: CallOverrides): Promise<[BigNumber]>;

    governance(overrides?: CallOverrides): Promise<[string]>;

    isUserTrustee(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    paused(overrides?: CallOverrides): Promise<[boolean]>;

    tokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & {
        token: string;
        hashedToken: string;
        approved: boolean;
      }
    >;

    trustees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean] & {
        trustee: string;
        trustor: string;
        createdAt: BigNumber;
        isTrusted: boolean;
      }
    >;

    userCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    userExists(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    userTrusteeCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, boolean] & {
        joined: BigNumber;
        updatedAt: BigNumber;
        hashedUser: string;
        verified: boolean;
      }
    >;

    __CampaignFactory_init(
      _governance: string,
      _campaignImplementation: string,
      _campaignRequestImplementation: string,
      _campaignVoteImplementation: string,
      _campaignRewardImplementation: string,
      _config: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCampaignImplementation(
      _campaignImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCampaignRewardImplementation(
      _campaignRewardsImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCampaignRequestImplementation(
      _campaignRequestsImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCampaignVoteImplementation(
      _campaignVotesImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addFactoryTransactionConfig(
      _prop: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCampaignTransactionConfig(
      _prop: string,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setDefaultCommission(
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setCategoryCommission(
      _categoryId: BigNumberish,
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addToken(
      _token: string,
      _approved: boolean,
      _hashedToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleAcceptedToken(
      _token: string,
      _state: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    canManageCampaigns(
      _user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    receiveCampaignCommission(
      _campaign: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    signUp(
      _hashedUser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    userIsVerified(
      _user: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initiateUserTransfer(
      _user: string,
      _forSelf: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deactivateAccountTransfer(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    addTrustee(
      _trustee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeTrustee(
      _trusteeId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    toggleUserApproval(
      _user: string,
      _approval: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createCampaign(
      _categoryId: BigNumberish,
      _approved: boolean,
      _hashedCampaignInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    activateCampaign(
      _campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    approveCampaign(
      _campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    modifyCampaignCategory(
      _campaign: string,
      _newCategoryId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createCategory(
      _active: boolean,
      _title: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    modifyCategory(
      _categoryId: BigNumberish,
      _active: boolean,
      _title: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unpauseCampaign(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pauseCampaign(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  accountInTransit(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  accountTransitStartedBy(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<string>;

  approvedCampaignTransactionConfig(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  campaignCategories(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
      campaignCount: BigNumber;
      createdAt: BigNumber;
      updatedAt: BigNumber;
      title: string;
      active: boolean;
      exists: boolean;
    }
  >;

  campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

  campaignFactoryAddress(overrides?: CallOverrides): Promise<string>;

  campaignImplementation(overrides?: CallOverrides): Promise<string>;

  campaignRequestsImplementation(overrides?: CallOverrides): Promise<string>;

  campaignRevenueFromCommissions(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  campaignRewardsImplementation(overrides?: CallOverrides): Promise<string>;

  campaignTransactionConfig(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  campaignTransactionConfigList(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  campaignVotesImplementation(overrides?: CallOverrides): Promise<string>;

  campaigns(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
      owner: string;
      createdAt: BigNumber;
      updatedAt: BigNumber;
      category: BigNumber;
      hashedCampaignInfo: string;
      active: boolean;
      approved: boolean;
    }
  >;

  categoryCommission(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  categoryCount(overrides?: CallOverrides): Promise<BigNumber>;

  categoryTitleIsTaken(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  factoryRevenue(overrides?: CallOverrides): Promise<BigNumber>;

  governance(overrides?: CallOverrides): Promise<string>;

  isUserTrustee(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  tokens(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [string, string, boolean] & {
      token: string;
      hashedToken: string;
      approved: boolean;
    }
  >;

  trustees(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, boolean] & {
      trustee: string;
      trustor: string;
      createdAt: BigNumber;
      isTrusted: boolean;
    }
  >;

  userCount(overrides?: CallOverrides): Promise<BigNumber>;

  userExists(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  userTrusteeCount(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  users(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, string, boolean] & {
      joined: BigNumber;
      updatedAt: BigNumber;
      hashedUser: string;
      verified: boolean;
    }
  >;

  __CampaignFactory_init(
    _governance: string,
    _campaignImplementation: string,
    _campaignRequestImplementation: string,
    _campaignVoteImplementation: string,
    _campaignRewardImplementation: string,
    _config: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCampaignImplementation(
    _campaignImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCampaignRewardImplementation(
    _campaignRewardsImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCampaignRequestImplementation(
    _campaignRequestsImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCampaignVoteImplementation(
    _campaignVotesImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addFactoryTransactionConfig(
    _prop: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCampaignTransactionConfig(
    _prop: string,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setDefaultCommission(
    _numerator: BigNumberish,
    _denominator: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setCategoryCommission(
    _categoryId: BigNumberish,
    _numerator: BigNumberish,
    _denominator: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addToken(
    _token: string,
    _approved: boolean,
    _hashedToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleAcceptedToken(
    _token: string,
    _state: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  canManageCampaigns(
    _user: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  receiveCampaignCommission(
    _campaign: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  signUp(
    _hashedUser: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  userIsVerified(_user: string, overrides?: CallOverrides): Promise<boolean>;

  initiateUserTransfer(
    _user: string,
    _forSelf: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deactivateAccountTransfer(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  addTrustee(
    _trustee: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeTrustee(
    _trusteeId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  toggleUserApproval(
    _user: string,
    _approval: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createCampaign(
    _categoryId: BigNumberish,
    _approved: boolean,
    _hashedCampaignInfo: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  activateCampaign(
    _campaign: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  approveCampaign(
    _campaign: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  modifyCampaignCategory(
    _campaign: string,
    _newCategoryId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createCategory(
    _active: boolean,
    _title: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  modifyCategory(
    _categoryId: BigNumberish,
    _active: boolean,
    _title: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unpauseCampaign(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pauseCampaign(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    accountInTransit(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    accountTransitStartedBy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<string>;

    approvedCampaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    campaignCategories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        campaignCount: BigNumber;
        createdAt: BigNumber;
        updatedAt: BigNumber;
        title: string;
        active: boolean;
        exists: boolean;
      }
    >;

    campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

    campaignFactoryAddress(overrides?: CallOverrides): Promise<string>;

    campaignImplementation(overrides?: CallOverrides): Promise<string>;

    campaignRequestsImplementation(overrides?: CallOverrides): Promise<string>;

    campaignRevenueFromCommissions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignRewardsImplementation(overrides?: CallOverrides): Promise<string>;

    campaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignTransactionConfigList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    campaignVotesImplementation(overrides?: CallOverrides): Promise<string>;

    campaigns(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber, string, boolean, boolean] & {
        owner: string;
        createdAt: BigNumber;
        updatedAt: BigNumber;
        category: BigNumber;
        hashedCampaignInfo: string;
        active: boolean;
        approved: boolean;
      }
    >;

    categoryCommission(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    categoryCount(overrides?: CallOverrides): Promise<BigNumber>;

    categoryTitleIsTaken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    factoryRevenue(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<string>;

    isUserTrustee(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    tokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [string, string, boolean] & {
        token: string;
        hashedToken: string;
        approved: boolean;
      }
    >;

    trustees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, boolean] & {
        trustee: string;
        trustor: string;
        createdAt: BigNumber;
        isTrusted: boolean;
      }
    >;

    userCount(overrides?: CallOverrides): Promise<BigNumber>;

    userExists(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    userTrusteeCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, string, boolean] & {
        joined: BigNumber;
        updatedAt: BigNumber;
        hashedUser: string;
        verified: boolean;
      }
    >;

    __CampaignFactory_init(
      _governance: string,
      _campaignImplementation: string,
      _campaignRequestImplementation: string,
      _campaignVoteImplementation: string,
      _campaignRewardImplementation: string,
      _config: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    setCampaignImplementation(
      _campaignImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCampaignRewardImplementation(
      _campaignRewardsImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCampaignRequestImplementation(
      _campaignRequestsImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCampaignVoteImplementation(
      _campaignVotesImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    addFactoryTransactionConfig(
      _prop: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setCampaignTransactionConfig(
      _prop: string,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setDefaultCommission(
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setCategoryCommission(
      _categoryId: BigNumberish,
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    addToken(
      _token: string,
      _approved: boolean,
      _hashedToken: string,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleAcceptedToken(
      _token: string,
      _state: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    canManageCampaigns(
      _user: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    receiveCampaignCommission(
      _campaign: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    signUp(_hashedUser: string, overrides?: CallOverrides): Promise<void>;

    userIsVerified(_user: string, overrides?: CallOverrides): Promise<boolean>;

    initiateUserTransfer(
      _user: string,
      _forSelf: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    deactivateAccountTransfer(overrides?: CallOverrides): Promise<void>;

    addTrustee(_trustee: string, overrides?: CallOverrides): Promise<void>;

    removeTrustee(
      _trusteeId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    toggleUserApproval(
      _user: string,
      _approval: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    createCampaign(
      _categoryId: BigNumberish,
      _approved: boolean,
      _hashedCampaignInfo: string,
      overrides?: CallOverrides
    ): Promise<void>;

    activateCampaign(
      _campaign: string,
      overrides?: CallOverrides
    ): Promise<void>;

    approveCampaign(
      _campaign: string,
      overrides?: CallOverrides
    ): Promise<void>;

    modifyCampaignCategory(
      _campaign: string,
      _newCategoryId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createCategory(
      _active: boolean,
      _title: string,
      overrides?: CallOverrides
    ): Promise<void>;

    modifyCategory(
      _categoryId: BigNumberish,
      _active: boolean,
      _title: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unpauseCampaign(overrides?: CallOverrides): Promise<void>;

    pauseCampaign(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "CampaignActivation(address)"(
      campaign?: string | null
    ): CampaignActivationEventFilter;
    CampaignActivation(campaign?: string | null): CampaignActivationEventFilter;

    "CampaignApproval(address)"(
      campaign?: string | null
    ): CampaignApprovalEventFilter;
    CampaignApproval(campaign?: string | null): CampaignApprovalEventFilter;

    "CampaignCategoryChange(address,uint256)"(
      campaign?: string | null,
      newCategory?: null
    ): CampaignCategoryChangeEventFilter;
    CampaignCategoryChange(
      campaign?: string | null,
      newCategory?: null
    ): CampaignCategoryChangeEventFilter;

    "CampaignDefaultCommissionUpdated(uint256)"(
      commission?: null
    ): CampaignDefaultCommissionUpdatedEventFilter;
    CampaignDefaultCommissionUpdated(
      commission?: null
    ): CampaignDefaultCommissionUpdatedEventFilter;

    "CampaignDeployed(address,address,address,address,address,uint256,bool)"(
      factory?: null,
      campaign?: null,
      campaignRewards?: null,
      campaignRequests?: null,
      campaignVotes?: null,
      category?: null,
      approved?: null
    ): CampaignDeployedEventFilter;
    CampaignDeployed(
      factory?: null,
      campaign?: null,
      campaignRewards?: null,
      campaignRequests?: null,
      campaignVotes?: null,
      category?: null,
      approved?: null
    ): CampaignDeployedEventFilter;

    "CampaignImplementationUpdated(address)"(
      campaignImplementation?: string | null
    ): CampaignImplementationUpdatedEventFilter;
    CampaignImplementationUpdated(
      campaignImplementation?: string | null
    ): CampaignImplementationUpdatedEventFilter;

    "CampaignRequestImplementationUpdated(address)"(
      campaignRequestImplementation?: string | null
    ): CampaignRequestImplementationUpdatedEventFilter;
    CampaignRequestImplementationUpdated(
      campaignRequestImplementation?: string | null
    ): CampaignRequestImplementationUpdatedEventFilter;

    "CampaignRewardImplementationUpdated(address)"(
      campaignRewardImplementation?: string | null
    ): CampaignRewardImplementationUpdatedEventFilter;
    CampaignRewardImplementationUpdated(
      campaignRewardImplementation?: string | null
    ): CampaignRewardImplementationUpdatedEventFilter;

    "CampaignTransactionConfigUpdated(string,uint256)"(
      prop?: null,
      value?: null
    ): CampaignTransactionConfigUpdatedEventFilter;
    CampaignTransactionConfigUpdated(
      prop?: null,
      value?: null
    ): CampaignTransactionConfigUpdatedEventFilter;

    "CampaignVoteImplementationUpdated(address)"(
      campaignVoteImplementation?: string | null
    ): CampaignVoteImplementationUpdatedEventFilter;
    CampaignVoteImplementationUpdated(
      campaignVoteImplementation?: string | null
    ): CampaignVoteImplementationUpdatedEventFilter;

    "CategoryAdded(uint256,bool,string)"(
      categoryId?: BigNumberish | null,
      active?: null,
      title?: null
    ): CategoryAddedEventFilter;
    CategoryAdded(
      categoryId?: BigNumberish | null,
      active?: null,
      title?: null
    ): CategoryAddedEventFilter;

    "CategoryCommissionUpdated(uint256,uint256)"(
      categoryId?: BigNumberish | null,
      commission?: null
    ): CategoryCommissionUpdatedEventFilter;
    CategoryCommissionUpdated(
      categoryId?: BigNumberish | null,
      commission?: null
    ): CategoryCommissionUpdatedEventFilter;

    "CategoryModified(uint256,bool,string)"(
      categoryId?: BigNumberish | null,
      active?: null,
      title?: null
    ): CategoryModifiedEventFilter;
    CategoryModified(
      categoryId?: BigNumberish | null,
      active?: null,
      title?: null
    ): CategoryModifiedEventFilter;

    "Paused(address)"(account?: null): PausedEventFilter;
    Paused(account?: null): PausedEventFilter;

    "TokenAdded(address,bool)"(
      token?: string | null,
      approval?: null
    ): TokenAddedEventFilter;
    TokenAdded(token?: string | null, approval?: null): TokenAddedEventFilter;

    "TokenApproval(address,bool)"(
      token?: string | null,
      state?: null
    ): TokenApprovalEventFilter;
    TokenApproval(
      token?: string | null,
      state?: null
    ): TokenApprovalEventFilter;

    "TrusteeAdded(uint256,address)"(
      trusteeId?: BigNumberish | null,
      trusteeAddress?: null
    ): TrusteeAddedEventFilter;
    TrusteeAdded(
      trusteeId?: BigNumberish | null,
      trusteeAddress?: null
    ): TrusteeAddedEventFilter;

    "TrusteeRemoved(uint256,address)"(
      trusteeId?: BigNumberish | null,
      trusteeAddress?: null
    ): TrusteeRemovedEventFilter;
    TrusteeRemoved(
      trusteeId?: BigNumberish | null,
      trusteeAddress?: null
    ): TrusteeRemovedEventFilter;

    "Unpaused(address)"(account?: null): UnpausedEventFilter;
    Unpaused(account?: null): UnpausedEventFilter;

    "UserAdded(address)"(userId?: string | null): UserAddedEventFilter;
    UserAdded(userId?: string | null): UserAddedEventFilter;

    "UserApproval(address,bool)"(
      user?: string | null,
      approval?: null
    ): UserApprovalEventFilter;
    UserApproval(
      user?: string | null,
      approval?: null
    ): UserApprovalEventFilter;
  };

  estimateGas: {
    accountInTransit(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    accountTransitStartedBy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    approvedCampaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignCategories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignCount(overrides?: CallOverrides): Promise<BigNumber>;

    campaignFactoryAddress(overrides?: CallOverrides): Promise<BigNumber>;

    campaignImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    campaignRequestsImplementation(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignRevenueFromCommissions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignRewardsImplementation(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignTransactionConfigList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    campaignVotesImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    campaigns(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    categoryCommission(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    categoryCount(overrides?: CallOverrides): Promise<BigNumber>;

    categoryTitleIsTaken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    factoryRevenue(overrides?: CallOverrides): Promise<BigNumber>;

    governance(overrides?: CallOverrides): Promise<BigNumber>;

    isUserTrustee(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    tokens(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    trustees(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    userCount(overrides?: CallOverrides): Promise<BigNumber>;

    userExists(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    userTrusteeCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    users(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    __CampaignFactory_init(
      _governance: string,
      _campaignImplementation: string,
      _campaignRequestImplementation: string,
      _campaignVoteImplementation: string,
      _campaignRewardImplementation: string,
      _config: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCampaignImplementation(
      _campaignImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCampaignRewardImplementation(
      _campaignRewardsImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCampaignRequestImplementation(
      _campaignRequestsImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCampaignVoteImplementation(
      _campaignVotesImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addFactoryTransactionConfig(
      _prop: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCampaignTransactionConfig(
      _prop: string,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setDefaultCommission(
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setCategoryCommission(
      _categoryId: BigNumberish,
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addToken(
      _token: string,
      _approved: boolean,
      _hashedToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleAcceptedToken(
      _token: string,
      _state: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    canManageCampaigns(
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    receiveCampaignCommission(
      _campaign: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    signUp(
      _hashedUser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    userIsVerified(
      _user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initiateUserTransfer(
      _user: string,
      _forSelf: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deactivateAccountTransfer(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    addTrustee(
      _trustee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeTrustee(
      _trusteeId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    toggleUserApproval(
      _user: string,
      _approval: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createCampaign(
      _categoryId: BigNumberish,
      _approved: boolean,
      _hashedCampaignInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    activateCampaign(
      _campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    approveCampaign(
      _campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    modifyCampaignCategory(
      _campaign: string,
      _newCategoryId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createCategory(
      _active: boolean,
      _title: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    modifyCategory(
      _categoryId: BigNumberish,
      _active: boolean,
      _title: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unpauseCampaign(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pauseCampaign(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accountInTransit(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    accountTransitStartedBy(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    approvedCampaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignCategories(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    campaignFactoryAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignRequestsImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignRevenueFromCommissions(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignRewardsImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignTransactionConfig(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignTransactionConfigList(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaignVotesImplementation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    campaigns(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    categoryCommission(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    categoryCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    categoryTitleIsTaken(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factoryRevenue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isUserTrustee(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokens(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    trustees(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    userExists(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    userTrusteeCount(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    users(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    __CampaignFactory_init(
      _governance: string,
      _campaignImplementation: string,
      _campaignRequestImplementation: string,
      _campaignVoteImplementation: string,
      _campaignRewardImplementation: string,
      _config: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCampaignImplementation(
      _campaignImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCampaignRewardImplementation(
      _campaignRewardsImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCampaignRequestImplementation(
      _campaignRequestsImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCampaignVoteImplementation(
      _campaignVotesImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addFactoryTransactionConfig(
      _prop: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCampaignTransactionConfig(
      _prop: string,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setDefaultCommission(
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setCategoryCommission(
      _categoryId: BigNumberish,
      _numerator: BigNumberish,
      _denominator: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addToken(
      _token: string,
      _approved: boolean,
      _hashedToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleAcceptedToken(
      _token: string,
      _state: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    canManageCampaigns(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    receiveCampaignCommission(
      _campaign: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    signUp(
      _hashedUser: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    userIsVerified(
      _user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initiateUserTransfer(
      _user: string,
      _forSelf: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deactivateAccountTransfer(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    addTrustee(
      _trustee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeTrustee(
      _trusteeId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    toggleUserApproval(
      _user: string,
      _approval: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createCampaign(
      _categoryId: BigNumberish,
      _approved: boolean,
      _hashedCampaignInfo: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    activateCampaign(
      _campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    approveCampaign(
      _campaign: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    modifyCampaignCategory(
      _campaign: string,
      _newCategoryId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createCategory(
      _active: boolean,
      _title: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    modifyCategory(
      _categoryId: BigNumberish,
      _active: boolean,
      _title: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unpauseCampaign(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pauseCampaign(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
