/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Factory, FactoryInterface } from "../Factory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "campaignFactory",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "governance",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "campaignImplementation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "campaignRequestImplementation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "campaignVoteImplementation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "campaignRewardImplementation",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "campaignIndex",
        type: "uint256",
      },
    ],
    name: "CampaignFactoryDeployed",
    type: "event",
  },
  {
    inputs: [],
    name: "deployedCampaignCount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "deployedCampaigns",
    outputs: [
      {
        internalType: "address",
        name: "factory",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_campaignFactoryImplementation",
        type: "address",
      },
      {
        internalType: "address",
        name: "_campaignImplementation",
        type: "address",
      },
      {
        internalType: "address",
        name: "_campaignRequestImplementation",
        type: "address",
      },
      {
        internalType: "address",
        name: "_campaignVoteImplementation",
        type: "address",
      },
      {
        internalType: "address",
        name: "_campaignRewardImplementation",
        type: "address",
      },
      {
        internalType: "address",
        name: "_governance",
        type: "address",
      },
      {
        internalType: "uint256[15]",
        name: "_config",
        type: "uint256[15]",
      },
    ],
    name: "createCampaignFactory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Factory__factory {
  static readonly abi = _abi;
  static createInterface(): FactoryInterface {
    return new utils.Interface(_abi) as FactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Factory {
    return new Contract(address, _abi, signerOrProvider) as Factory;
  }
}
