import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState, useEffect } from 'react'
import Web3 from 'web3'

import { onboard, CORE_FACTORY } from '@/connectors'
import { Header } from '@/components/Header'

const Home: NextPage = () => {
  const fetchContractAddress = async () => {
    const { address } = onboard.getState();
    try {
      await CORE_FACTORY.methods
      .createCampaignFactory('0x9561C133DD8580860B6b7E504bC5Aa500f0f06a7', address)
      .send({ from: address })
    } catch(error) {
      console.log(error)
    }
    console.log(await CORE_FACTORY.methods.deployedCampaignCount().call())
    // CORE_FACTORY.events.CampaignFactoryDeployed({}, { fromBlock: 0, toBlock: 'latest' }).on(
    //   'data', function(event: any) {
    //   console.log(event);
    // }).on('error', console.error);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <button onClick={fetchContractAddress}>Test</button>
      </main>
    </div>
  )
}

export default Home
